name: Publish release

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Publish release
        run: gh release create --repo $GITHUB_REPOSITORY Release_$GITHUB_SHA
        env:
          GH_TOKEN: ${{ github.token }}